name: Mutants

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  cargo-mutants:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@ecabd13d1c56bd1345c230e542e9144811ad706f # v2.0.0
        with:
          toolchain: stable
      - uses: taiki-e/install-action@83ac0ad63c0167e6f06796fab0fce28db1bf3db0 # v2.87.22
        with:
          tool: cargo-mutants
      - run: sudo apt-get install -y gnome-keyring
      - run: gnome-keyring-daemon --components=secrets --daemonize --unlock <<< 'foobar'
      - env:
          BASE_REF: ${{ github.base_ref }}
        run: git diff origin/"$BASE_REF"...HEAD > pr.diff
      - run: cargo mutants --in-diff pr.diff --features crypto-rust -j 2
